# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
