# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_room',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_count', models.IntegerField(default=0)),
                ('visitor_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('person_count', models.IntegerField(default=1)),
                ('purpose', models.TextField()),
                ('booking_from', models.DateField()),
                ('Booking_to', models.DateField()),
                ('status', models.CharField(choices=[('Confirm', 'Confirm'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=10)),
                ('remark', models.CharField(blank=True, max_length=40)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('opening_stock', models.IntegerField(default=0)),
                ('addition_stock', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('serviceable', models.IntegerField(default=0)),
                ('non_serviceable', models.IntegerField(default=0)),
                ('inuse', models.IntegerField(default=0)),
                ('total_usable', models.IntegerField(default=0)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('morning_tea', models.BooleanField(default=False)),
                ('eve_tea', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=4, unique=True)),
                ('room_type', models.CharField(choices=[('SingleBed', 'SingleBed'), ('DoubleBed', 'DoubleBed')], max_length=12)),
                ('room_floor', models.CharField(choices=[('GroundFloor', 'GroundFloor'), ('FirstFloor', 'FirstFloor'), ('SecondFloor', 'SecondFloor'), ('ThirdFloor', 'ThirdFloor')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('CheckedIn', 'CheckedIn'), ('Available', 'Available'), ('UnderMaintenance', 'UnderMaintenance')], default='Available', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=40)),
                ('visitor_email', models.CharField(max_length=40)),
                ('visitor_phone', models.CharField(max_length=12)),
                ('visitor_address', models.TextField()),
                ('nationality', models.CharField(max_length=20)),
                ('intender_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_bill', models.IntegerField(default=0)),
                ('room_bill', models.IntegerField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
                ('caretaker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Room')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='room_status',
            name='br_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Visitor'),
        ),
        migrations.AddField(
            model_name='meal',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Visitor'),
        ),
        migrations.AddField(
            model_name='book_room',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Visitor'),
        ),
    ]
