# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_status',
            name='room_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Room'),
            preserve_default=False,
        ),
    ]
