# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0002_room_status_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='intender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
