# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0003_auto_20171029_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_room',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room_status',
            name='br_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor_hostel.Book_room'),
        ),
    ]
