# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0004_auto_20171030_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='persons',
            field=models.IntegerField(default=0),
        ),
    ]
