# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_hostel', '0005_meal_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_bill',
            name='caretaker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
