# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0002_auto_20171029_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('file_type', models.CharField(choices=[('HardCopy', 'HardCopy'), ('SoftCopy', 'SoftCopy')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'resolved'), ('1', 'notresolved')], default=1)),
                ('leave_flag', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('resolve_date', models.DateTimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='globals.ExtraInfo')),
                ('substitute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_id', to='globals.ExtraInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField()),
                ('forward_date', models.DateTimeField()),
                ('remark', models.CharField(max_length=250)),
                ('forward_flag', models.BooleanField(default=False)),
                ('current_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.ExtraInfo')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_tracking.File')),
            ],
        ),
    ]
